name: release-please

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # Usamos tu token personalizado para disparar otros workflows si es necesario
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          target-branch: ${{ github.ref_name }}

